import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
   

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // 🔥 لو فتحت على Web (مؤقت)
      return android; // استخدم نفس إعدادات Android مؤقتًا
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      default:
        throw UnsupportedError('This platform is not configured for Firebase');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNopS-E6XDyzj7zJjogf8e0kI5Q8llFWE',
    appId: '1:1096778352660:android:faaf5722a4958be8ddbf01',
    messagingSenderId: '1096778352660',
    projectId: 'healthy-app-chat',
    storageBucket: 'healthy-app-chat.firebasestorage.app',
  );
}
// import 'package:flutter/foundation.dart'
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyClJVknl5SMlC0szutrjuahGVCqQZb3ujU',
//     appId: '1:684731767294:web:8a28fd151453f0339b48af',
//     messagingSenderId: '684731767294',
//     projectId: 'healthylifeapp-e2e37',
//     authDomain: 'healthylifeapp-e2e37.firebaseapp.com',
//     storageBucket: 'healthylifeapp-e2e37.firebasestorage.app',
//     measurementId: 'G-7MHGM7ML8J',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyC1Nt3UEh2HOHT4TEnuDnHZQMYUDTh2NZs',
//     appId: '1:684731767294:android:f21aee315e7618e49b48af',
//     messagingSenderId: '684731767294',
//     projectId: 'healthylifeapp-e2e37',
//     storageBucket: 'healthylifeapp-e2e37.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyA0e0FkwSkUtPJqu4lX5vdYi4UJF-SXIcc',
//     appId: '1:684731767294:ios:4bb3a1aa076272cf9b48af',
//     messagingSenderId: '684731767294',
//     projectId: 'healthylifeapp-e2e37',
//     storageBucket: 'healthylifeapp-e2e37.firebasestorage.app',
//     iosBundleId: 'com.example.example1',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyA0e0FkwSkUtPJqu4lX5vdYi4UJF-SXIcc',
//     appId: '1:684731767294:ios:4bb3a1aa076272cf9b48af',
//     messagingSenderId: '684731767294',
//     projectId: 'healthylifeapp-e2e37',
//     storageBucket: 'healthylifeapp-e2e37.firebasestorage.app',
//     iosBundleId: 'com.example.example1',
//   );
// }
